heat_template_version: 2015-04-30

parameters:
  key_name:
    type: string
    label: KeyName
  image_id:
    type: string
    label: ImageID
  instance_type:
    type: string
    label: InstanceType

resources:
  instance0001:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
