heat_template_version: 2021-04-16

description: "Server Setup"

parameters:
  server_0001_name:
    type: string
    label: "Server 0001 Name"
    description: "Name of Server 0001"
    default: "sr0001.network-0001.os-cloud-0001.vty-valentin-vty.net"
  server_0001_name_adminpass:
    type: string
    label: "Server 0001 Admin Password"
    description: "Admin Password of Server 0001"
    hidden: true

resources:
  server_0001:
    type: OS::Nova::Server
    properties:
      flavor:
      admin_pass: { get_param: server_0001_name_adminpass }
      availability_zone:
      block_device_mapping_v2:
        delete_on_termination: false
        device_name:
        volume_size:
        boot_index:
      image: { get_param: server_0001_image }
      key_name: { get_param: server_0001_keyname }
      name: { get_param: server_0001_name }
      networks:
        fixed_ip:
        floating_ip:
        network:
        port_extra_properties:
          admin_state_up:
          mac_address:
        subnet:
      security_groups:
      user_data_format: RAW
      user_data: |
        #!/bin/bash
        echo "server-0001" > /etc/hostname
        hostname server-0001
        apt update
        apt install -y git curl wget openstack-clients vim awscli
  