heat_template_version: 2021-04-16

description: "Networking Setup"

parameters:
  network_0001_name:
    type: string
    label: "Network 0001 Name"
    description: "Name of Network 0001"
    default: "network-0001.os-cloud-0001.vty-valentin-vty.net"
  network_0001_dns:
    type: string
    label: "Network 0001 DNS Name"
    description: "DNS Name of Network 0001. Can be set under network-properties with dns_domain"
    default: "network-0001.os-cloud-0001.vty-valentin-vty.net"
  network_0001_subnet_0001_cidr:
    type: string
    label: "Subnet 0001 of Network 0001 CIDR (IPv4)""
    description: "IPv4 CIDR of Subnet 0001 in Network 0001"
    default: ""
  network_0001_subnet_0002_cidr:
    type: string
    label: "Subnet 0002 of Network 0001 CIDR (IPv4)""
    description: "IPv4 CIDR of Subnet 0002 in Network 0001"
    default: ""
  network_0001_subnet_0003_cidr:
    type: string
    label: "Subnet 0003 of Network 0001 CIDR (IPv6)""
    description: "IPv6 CIDR of Subnet 0003 in Network 0001"
    default: ""
  network_0001_subnet_0004_cidr:
    type: string
    label: "Subnet 0004 of Network 0001 CIDR (IPv6)""
    description: "IPv6 CIDR of Subnet 0004 in Network 0001"
    default: ""

resources:
  network_0001:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: { get_param: network_0001_name }
      
  network_0001_subnet_0001:
    type: OS::Neutron::Subnet
    properties:
      name: subnet-0001-{ get_param: network_0001_name }
      network: { get_resource: network_0001 }
      ip_version: 4
      cidr: { get_param: network_0001_subnet_0001_cidr }
      
  network_0001_subnet_0002:
    type: OS::Neutron::Subnet
    properties:
      name: subnet-0002-{ get_param: network_0001_name }
      network: { get_resource: network_0001 }
      ip_version: 4
      cidr: { get_param: network_0001_subnet_0002_cidr }

  network_0001_subnet_0003:
    type: OS::Neutron::Subnet
    properties:
      name: subnet-0003-{ get_param: network_0001_name }
      network: { get_resource: network_0001 }
      ip_version: 6
      cidr: { get_param: network_0001_subnet_0003_cidr }
      
  network_0001_subnet_0004:
    type: OS::Neutron::Subnet
    properties:
      name: subnet-0004-{ get_param: network_0001_name }
      network: { get_resource: network_0001 }
      ip_version: 6
      cidr: { get_param: network_0001_subnet_0004_cidr }
      
  dnszone_0001:
    type: OS::Designate::Zone
    properties:
      name: "vty-valentin-vty.net."
      email: "hostmaster@vty-valentin-vty.oscloud"
      
  dnszone_0001_record_0001:
    type: OS::Designate::RecordSet
    properties:
      zone: { get_resource: dnszone_0001 }
      type: TXT
      name: root
    depends_on:
      - dnszone_0001
      
  secgroup_0001:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - direction: ingress
          ethertype: IPv4
          protocol: tcp
          remote_mode: remote_ip_prefix
          remote_ip_prefix: "0.0.0.0/0"
          port_range_min: 22
          port_range_max: 22
        - direction: ingress
          ethertype: IPv6
          protocol: tcp
          remote_mode: remote_ip_prefix
          remote_ip_prefix: "::/0"
          port_range_min: 22
          port_range_max: 22
      name: "sg-0001"
      description: "allow ssh via ipv6 and ipv4 from everywhere"
      
  secgroup_0002:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - direction: ingress
          ethertype: IPv4
          remote_mode: remote_ip_prefix
          remote_ip_prefix: "0.0.0.0/0"
        - direction: ingress
          ethertype: IPv6
          remote_mode: remote_ip_prefix
          remote_ip_prefix: "::/0"
      name: "sg-0002"
      description: "allow all traffic via ipv6 and ipv4 from everywhere"
      
  secgroup_0003:
    type: OS::Neutron::SecurityGroup
    properties:
      name: "sg-0003"
      description: "allow no traffic via ipv6 and ipv4"
